apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wiz457sol-python
  janus-idp.io/tekton: wiz457sol-python
  backstage.io/kubernetes-id: wiz457sol-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wiz457sol-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
