apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wiz457sol-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wiz457sol-python 
  name: wiz457sol-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wiz457sol-python 
